### ISSUE TITLE
403 Forbidden when attempting to create a new asset revision

### ISSUE THREAD

**Issue by NathanHowell** [AdobeDocs/lightroom-partner-apis#103]
I am wondering if it is possible to create a new revision on an existing asset? I'm trying to implement a map module to add location information from a GPS track to existing images. The revision API appears to only allow creating a revision on a new asset. Attempting to create a new revision on an existing asset fails with 403.

If this functionality was exposed as a `PUT` or `PATCH` I could easily implement a fix for https://feedback.photoshop.com/conversations/lightroom-desktop-cloudbased/lightroom-desktop-map-viewmodule-ability-to-geotag-photos/5f5f45dd4b561a3d4263e0d6 as well as adapting the reverse geocoding to work better for hiking destinations - lakes, mountains, rivers, etc - not just the nearest city.

**Comment by slohia-adobe** [comment]
@NathanHowell Sorry for the late reply here. The functionality to create revision on an existing asset is not allowed currently.

**Comment by NathanHowell** [comment]
@slohia-adobe yes, I realize that - the 403 makes it clear. is there a better place to request this functionality? I think it would open up a lot of really nice features.

**Comment by slohia-adobe** [comment]
@NathanHowell Yes, this is the correct place to make the request. At this point, this functionality is not available. But your feature request has been noted for the future.

**Comment by NathanHowell** [comment]
@slohia-adobe is the underlying issue fixed now? I'd still really like to add gps track support
