### ISSUE TITLE
403 forbbiden access when attempting to generate rendition

### ISSUE THREAD

**Issue by dingran** [AdobeDocs/lightroom-partner-apis#117]
### Expected Behaviour
According to the documentation here https://www.adobe.io/apis/creativecloud/lightroom/apidocs.html#/assets/generateRenditions

We can POST to `/v2/catalogs/{catalog_id}/assets/{asset_id}/renditions` to generate renditions of `fullsize` or `2560`

One thing that is a bit confusing in the doc is that the required parameters `X-Generate-Renditions` looks like should be in the **header** but the doc says it is in the **path**

![image](https://user-images.githubusercontent.com/12864782/103493124-8a763780-4dfd-11eb-8ae8-c9193e4b011a.png)

So I tried both

1. POST to `/v2/catalogs/{catalog_id}/assets/{asset_id}/renditions/2560` with Authorization and X-API-Key in the header
2. POST to `/v2/catalogs/{catalog_id}/assets/{asset_id}/renditions` with Authorization and X-API-Key, and `X-Generate-Renditions: 2560` in the header 

In one of the ase, I should have received 202 status  with a rendition link

### Actual Behaviour

**With method 1, I received the following response**

````html
<html>

<head>
	<title>403 Forbidden</title>
</head>

<body>
	<center>
		<h1>403 Forbidden</h1>
	</center>
	<hr>
	<center>openresty</center>
</body>

</html>
````

**With method 2, I received the following response**

````javascript
while (1) {}
{
    "code": 4300,
    "description": "Access is forbidden"
}
````

#### Steps to Reproduce

In Postman, do 1 or 2 below

1. POST to `/v2/catalogs/{catalog_id}/assets/{asset_id}/renditions/2560` with Authorization and X-API-Key in the header

![image](https://user-images.githubusercontent.com/12864782/103493308-8bf42f80-4dfe-11eb-8230-620b706b96af.png)

2. POST to `/v2/catalogs/{catalog_id}/assets/{asset_id}/renditions` with Authorization and X-API-Key, and `X-Generate-Renditions: 2560` in the header 

![image](https://user-images.githubusercontent.com/12864782/103493321-99111e80-4dfe-11eb-92c4-06b20935224c.png)

**Comment by slohia-adobe** [comment]
@dingran 'X-Generate-Renditions' will be a header and it is corrected now. Also Generating Renditions using that API requires special permission to be present on the client_id. Will get back to you on this.

**Comment by slohia-adobe** [comment]
@dingran Since this API requires special permissions given to the client. Without that this API will return 403 only, so we wanted to understand your requirement with respect to rendition generation here.

**Comment by dingran** [comment]
@slohia-adobe I'm making an app to connect to Lightroom album and render assets in it as a gallery at a destination website, for this gallery view small rendition size is fine (e.g. thumbnail for grid view and 1024 for expanded view). Then for each photo in the gallery, a user can select to download/export large rendition for printing, depending on the print size, fullsize or 2560 rendition will be needed.

**Comment by pbaust** [comment]
@dingran Thanks for the info and your interest in our APIs.  We are making the additional APIs available to all partners and solutions that “Do not duplicate/shadow the core functionality of Lightroom.” .  Can you talk about how your app will be unique in its use of the Lightroom Public APIs, and differentiated from current Lightroom capabilities?

-Peter

**Comment by dingran** [comment]
hey @pbaust , I'm building this as a personal project to begin with, as a photographer and lightroom user myself, here are what I wanted to achieve

1. I want to share publicly one or more galleries at my own website that can pull my Lightroom albums (I can still do all the editing inside LR). Since I own the functionality of my website, I can add various ways to search/discover my galleries and photos and they would share the same UX as the rest of the site.
2. some times my friend ask me for photos to print out, I want to let them to be able to pick which photos they like from my gallery and export a large version for printing (optionally, I can also ask strangers who wanted my photo to pay for it by putting up a paywall for this).
3. Both of the above could be extended to support other users who wants to connect Lightroom albums to their own website (or hosted by me site).

Lightroom is an excellent editing tool and is very good when I share albums with friend who already use Lightroom, or use its provided web link. But I didn't find obvious ways to embed the gallery in my own site and also support transactions on individual photos (paid export for example).

Hope this is helpful.

**Comment by pbaust** [comment]
Thanks for the additional info.  We are considering your request and will get back to you shortly.

-Peter

**Comment by slohia-adobe** [comment]
@dingran Can you please share your api key.

**Comment by dingran** [comment]
`25148704b2fb4b99a6ec49fd82d7a1d8`

**Comment by pbaust** [comment]
We have granted you access to this API.  Usage of the API may be limited, and we request that you use it on an as needed basis only.  Please let us know if you see any issues.

-Peter

**Comment by dingran** [comment]
Awesome, thanks!

**Comment by klefix** [comment]
Hi, I need this as well!
I am creating a Tool to export Photos from selected Albums to Google Photos for sharing/viewing.
Therefore I wanted to create full-size renditions and stumbled upon the `403 Forbidden`.
What is the usual process of acquiring permissions to generate renditions? 
I stumbled upon this closed issue by googling for hours and couldn't find any docs about why I might get 403 when everything else works... :thinking:

**Comment by pbaust** [comment]
We are considering your request and will get back to you shortly.

-Peter

**Comment by slohia-adobe** [comment]
@klefix 
- Please also include the scope "lr_partner_rendition_apis" while requesting token as mentioned in docs - https://developer.adobe.com/lightroom/lightroom-api-docs/getting-started/authenticate_customers/
- If you get an error while requesting token with that additional scope and please create a new client_id from adobe developer console. With the new client_id it should work fine if it doesn't work with new client_id

Let me know if you face any issues post
