### ISSUE TITLE
4300 "Access is forbidden"  when attempting to post to renditions end point

### ISSUE THREAD

**Issue by calebmitcler** [AdobeDocs/lightroom-partner-apis#140]
I need to get fullsize rendition of asset to print. For assets that do not have a fullsize rendition link under links{. . .} i try to post to this [endpoint](https://www.adobe.io/apis/creativecloud/lightroom/apidocs.html#!docs/api/LightroomPartnerAPIsSpec.json) 
The description states: 
> Generate renditions for an original file asynchronously. Allowed rendition types are fullsize and 2560. Generated rendition will be deleted after 1 day automatically.

I assume this post would create a rels/rendition_type/fullsize . The response i get back in postman is 4300, Access is forbidden. In my application i get 403.

 Maybe this has something to do with the scopes i'm using to get oAuth token: openid lr_partner_apis. Whenever i try to use creative_sdk in the scope the request fails. Is this how i get fullsize version of images? if so, why is request failing. All the GET requests go through just fine. It's only this post that is returning error

**Comment by slohia-adobe** [comment]
@calebmitcler This API requires special permissions to be granted. Can you please share your API key.

**Comment by calebmitcler** [comment]
Thank you for fast response. I sent email to slohia@adobe.com with api key

**Comment by slohia-adobe** [comment]
@calebmitcler Can you try now.

**Comment by calebmitcler** [comment]
Hello! i still receive 4300 "Access is forbidden"

**Comment by slohia-adobe** [comment]
Ok will check.
