### ISSUE TITLE
lr_partner_rendition_apis

### ISSUE THREAD

**Issue by calebmitcler** [AdobeDocs/lightroom-partner-apis#169]
Hello, our test client needs access to lr_partner_rendition_apis scope

Sometimes we notice api performance issues. Whenever we need to GET an image. We first post to the rendition endpoint to make sure the image has fullsize or 2560 available. Sometimes the get image returns 404, even though the post succeeds. We suspect there might be a rate limit? Our app is in beta, and we call the api thousands of times a day. When the app is released this will probably be hundreds of thousands/day. 

I can email you our api keys

**Comment by slohia-adobe** [comment]
@calebmitcler Thanks for your interest. lr_partner_rendition_apis scope was granted to one of your client_ids earlier. Can you please explain us the use case to have it enabled on the second client id. Thanks.

**Comment by calebmitcler** [comment]
We would like to have separate keys for development and production. In case there is a rate limit, we don't want development to interfere with production

**Comment by slohia-adobe** [comment]
@calebmitcler Can you please refer to this Doc to understand the rendition flow -https://www.adobe.io/apis/creativecloud/lightroom/docs.html#!quickstart/renditions.md

 By default when an image is uploaded, the below renditions are being generated automatically. 

1. thumbnail2x (320 pixels constraint on either edge)
2. 640 (640 pixels on long edge)
3. 1280 (1280 pixels on long edge)
4. 2048 (2048 pixels on long edge)

Above renditions will serve all the usecases. 2560 and fullsize renditions are only meant for print purposes and are generated asynchronously that is why you get a 404. Please refer to the diagram at this link to understand how you need to poll and wait for these renditions to get genearted.

**Comment by slohia-adobe** [comment]
Also can you please share the other api-key for which you want to lr_partner_rendition_apis scope.

**Comment by calebmitcler** [comment]
Thank you!! Our test api key is d31406efa36741c791b30fa2a44b0a84

**Comment by slohia-adobe** [comment]
@calebmitcler Can you check now. Also did you check the link related to renditions which I shared. Are there any doubts?

**Comment by calebmitcler** [comment]
Sorry for late response. everything looks good. Thank you for your help!
